server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6380
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: nurl.ink:8003
  stats:
    locale:
      amap-key: ${SHORT_LINK_AMAP_KEY:6bb09f52782c146e97ef32db47713624}
      dev-fallback-ip: 14.215.177.39
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园,GitHub,哔哩哔哩'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - github.com
        - bilibili.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
